# Generated by Django 4.2.6 on 2023-10-12 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reminder", "0006_eventinstance_is_complete_alter_user_is_married"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entity",
            options={
                "ordering": ["name"],
                "verbose_name": "Entity",
                "verbose_name_plural": "Entities",
            },
        ),
    ]
