# Generated by Django 4.2.6 on 2023-10-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reminder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="entities",
            field=models.ManyToManyField(related_name="events", to="reminder.entity"),
        ),
    ]
