# Generated by Django 4.2.6 on 2023-10-12 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reminder", "0002_alter_event_entities"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
