# Generated by Django 4.2.6 on 2023-10-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reminder", "0003_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["remaining_time"]},
        ),
        migrations.RemoveField(
            model_name="event",
            name="year_type",
        ),
        migrations.AddField(
            model_name="event",
            name="is_lunar_year",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(default="General", max_length=20),
        ),
        migrations.AlterField(
            model_name="event",
            name="recurrence",
            field=models.CharField(
                choices=[
                    ("없음", "none"),
                    ("매년", "year"),
                    ("매월", "month"),
                    ("매주", "week"),
                    ("매일", "day"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
