# Generated by Django 4.2.6 on 2023-10-12 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reminder", "0004_alter_notification_options_remove_event_year_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["remaining_days"]},
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="remaining_time",
            new_name="remaining_days",
        ),
    ]
