# Generated by Django 4.2.6 on 2023-10-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reminder", "0005_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventinstance",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_married",
            field=models.BooleanField(default=False),
        ),
    ]
